### ISSUE TITLE
[TODO] Computation time... and rough speedup

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#71]
For 1D,2D,3D, this is absolutely necessary.
For 2D, I'll compare with "pyscatwave" to which I'll compare(for which i have a rough idea of th espeedup w.r.t. MATLAB). Hopefully it'll be faster

CPU + GPU time

- [x] 1D, batches of size 128x1x262144, J=10, Q=8
- [x] 2D, batches of size 128x3x256x256, L=8, J=3
- [x] 3D, batches of size 2x128x128x128, L=2, J=2

E
