### ISSUE TITLE
JTFS laundry

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#712]
@lostanlen and I bulleted two threads; I'll organize unresolved points here. List probably incomplete, will update

### Unanswered (may add to Todo)

None
 
### Todo

 - [ ] 1. move implementation notes?
 - [ ] 2. performance guide?
 - [ ] 3. rebase into `new-dev`?
 - [ ] 4. merge `axis=None` fix in `UnifiedBackend`

<hr>

 - [x] ~1. Docs~
 - [x] ~5. PR breakdown~
 - [x] ~6. `conj_reflections` cpu calculations take significant time~
 - [x] ~6. Default `pad_factor_fr='zero'`? chk speed~
 - [x] ~5. SE~
 - [x] ~7. `pack_coeff_jtfs` freq ordering~
 - [x] ~2. rename `sc_freq`? -- `fscat` -- `scat_fr` -- `sf`~
 - [x] ~6. coverage~
 - [x] ~3. reconstruction converges faster than `scattering.m`'s?~
 - [x] ~9. examples~
 - [x] ~4. coefficient renormalization across samples~
 - [x] ~11. `nyquist_correction=False` for JTFS~
 - [x] 9.~ `J_pad_fr` -> `J_pad_frs`~
 - [x] ~4. review points~
 - [x] ~3. `shape_fr` -> `N_fr`?~
 - [x] ~4. `analytic`~
 - [x] ~2. Demo use case for `resample_* = False`~
 - [x] ~3. move pad update to jtfs~
 - [x] ~4. visuals test~
 - [x] ~11. `pack_coeffs_jtfs` w/ `out_exclude != None`~
 - [x] ~10. tuple `r_psi`~
 - [x] 7. `implementation`
 - [x] ~8. `JTFS(log(U1))`?~
 - [x] ~6. "temporal" -> "spatial"?~
 - [x] ~10. denormals~
 - [x] ~2. Ensure no boundary effects~
 - [x] ~9. 4D demo: `aligned`, `sampling_psi_fr`~
 - [x] ~11. `conj-reflect-zero` is worse than `zero` for FDTS? Even with `reflect`?~
 - [x] ~10. rework `xi_max`~
 - [x] ~8. check LP for `exclude` -- should `recalibrate` phi?~
 - [x] ~11. `fftshift` for `zoom=-1`?~
 - [x] ~7. out_4D~
 - [x] 7. ~"out_3D" and exclude? & docs~
 - [x] ~10. `validate_filterbank()` -- check if filters are well-behaved in time and freq domain: boundary effects, decay, analyticity, single peak, LP sum, etc~
 - [x] ~15. assert that every `j0` has at least one filter in `exclude`~
 - [x] ~10. energy-norm coeffs at compute?~
 - [x] ~14. stride energy correction?~
 - [x] ~7. torch reconstruction OOM (pseudo-iter to register; always keep `J_pad_fr_max_init` in general?)~
 - [x] ~7. global average pooling: enforce mean to not exceed `/ N`? or first unpad then take mean?~
 - [x] x~14. unpad_fr sooner if `log2_F < J_fr` per `n2` (same for time)~
 - [x] x~13. `average_fr_global[j0] = bool(pad_fr < phi_fr['j'])`?~
 - [x] x~17. `out_3D`: need not max pad for all, can just pad output~
 - [x] ~4. I/O energy test~
 - [x] ~9. test global averaging by comparing against `T=N-1` and `F=shape_fr_max - 1`~
 - [x] ~8. append stride as part of computed meta?~
 - [x] ~9. pad to max with `average_fr_global`?~
 - [x] ~8. `average=False` breaks~
 - [x] ~7. docs: true `aligned` requires `resample_=True`~
 - [x] ~12. backprop test~
 - [x] ~8. Dedicated edge case testing~
 - [x] ~6. Invariance tests~
 - [x] ~4. alt to zero padding JTFS: zero boundaries before `*phi_t` in `_joint_lowpass()`~
 - [x] ~2. Backends (patch up `dev`)~
 - [x] ~10. variable `n1_fr` per `n2`?~
 - [x] ~10. Does `aligned=True` permit `resample_*=False`?~
 - [x] ~11. `meta` neglects `*Phi` in tracking first order~
 - [x] ~12. `resample_psi_fr=False` aliases~
 - [x] ~13. can compute exact padding with `resample*=any`~
 - [x] ~14. `resample_psi_fr=False` creates duplicate or redundant filters ...~
 - [x] ~15. adjust filter meta based on `resample_`~
 - [x] ~16. rework `resample_=False`~
 - [x] ~2. ~Backends (done for now, must finish `torch` later along integration with `master`)~
 - [x] ~9. meta~
 - [x] ~10. move `_FrequencyScatteringBase` docs to `TimeFrequencyScatteringBase1D`?~
 - [x] ~11. `resample_*` we get to subsample more but `j` is less?~
 - [x] ~12. is a `max_subsample_before_psi_fr` needed? (i.e. pad restriction)~
 - [x] ~11. Detach `out_type` from computation logic~
 - [x] ~12. Is `sc_freq.ind_start_fr[-1]` unpad for `phi_t * phi_f` correct? (what if `psi_f` subsamples more)~
 - [x] ~25. undo accounting for non-CQT filter failure~
 - [x]  ~28. rework "no second order" edge case to only apply to JTFS~
 - [x]  ~29. `alpha`~
 - [x]  ~22. up is down~
 - [x]  ~17. Set `J_fr` default from `shape_fr_max`?~
 - [x]  ~18. Default `average_fr=False`~
 - [x]  ~26. `max_pad_factor_fr`~ test~
 - [x]  ~9. `resample_phi_fr=False`: not accounted for by `compute_minimum_support_to_pad`, will pad excessively. Unsure if any effects other than speed~
 - [x]  ~16. Test `average` & `average_fr` combos (also `oversampling`)~
 - [x]  ~25. `log2_F_fo < log2_F` edge case test~
 - [x]  ~27. Forbid `J_pad_fo > J_pad_max` with `resample_* = True`~
 - [x]  ~24. Ignore `F`, `T` with `average* = False`~
 - [x]  ~10. Should `not aligned and out_type == 'list'` be allowed? Unchecked~
 - [x]  ~6. Batched inputs~
 - [x]  ~19. Detect and set `T=2**N` -> `average="global"`~
 - [x]  ~11. 2-point DFT check (at lowpass)~
 - [x]  ~15. Merge `resample_psi_fr` & `resample_phi_fr` into tuple?~
 - [x]  ~21. `phi_t * phi_f` L1 abnormality~
 - [x]  ~20. `out_type = "array-like"` so shapes are like `"array"` but return list to avoid redundant concat~
 - [x]  ~7. Meta for various `out_type` & kwargs~
 - [x]  ~3. `average_fr` kwarg (and one more for FOTS freq avg?)~
 - [x]  ~4. `concatenate` first-order and JTFS coeffs separately?~
      ~- `* phi_t`: flatten joint along first-order~
      ~- `* phi_t * phi_f`: treat FO as a joint slice~
      ~- both: two arrays? `* phi_t` separately~
 - [x]  ~6. `F`~
 - [x]  ~16. `phi_t * psi_f` pairs: use all first-order coeffs? (also `psi_t * phi_f` doesn't use `J_fr - 1`)~
 - [x]  ~21. `resample_* = False` tests~
 - [x]  ~21. `phi`'s max `j` logic in factory~
 - [x]  ~22. `_fo` case test~
 - [x]  ~19. `sc_freq.phi_f` does global average pooling (bad resampling); also check `sc_freq.psi1_f`~
 - [x]  ~3. Global average pooling~
 - [x]  ~7. Zeroth-order~
 - [x]  ~19. check filterbank energies~
 - [x]  ~11.`Q2 > 1`~  
 - [x] ~4. `padlen(S_1) > padlen(Y_2)` case~
 - [x]  ~4. Resampled `sc_freq.psi1_f`~
 - [x]  ~5. Variable padding amounts for `Y_2_list`~
 - [x]  ~6. Correct padding boundaries for `Y_2_list`~
 - [x]  ~6. `oversample_fr` kwarg? (different from current)~
 - [x]  ~8. `phi_f` resampling/subsampling rate for variable padding~
 - [x]  ~11. `sc_freq` may lack short enough filters given wide range of `shape_fr` (reproducible with `T=2**16, J=14, Q=16`)~

### Todo (non-JTFS)

 - [ ] 1. `periodize_filter_fourier`: 
```
which has the effect of `h_t[::k]`, where `h_t = ifft(h_f)`.
````
 - [ ] 2. `scattering_filter_factory`'s `**kwargs` does nothing
 - [ ] 3. `ceil`
 - [ ] 4. "subsamp in time <=> ~periodization~ folding in Fourier"
 - [ ] 5. dict returns where lists suffice (or wrong docs)
 - [ ] 6. Move `out_type` checks to base frontend
 - [ ] 7. Idea re: JTFS tests long: run only if relevant source files changed. Run method on top of `test_jtfs.py` to detect, against previously stored binary file of sources

<hr>

 - [x] 5. ~For `T`, if `average=False`, override and set to `2**J` so it doesn't interfere with subsampling (+ throw warning that it does nothing)~
 - [x] ~11. document "pad length is x16 `2**J`"~
 - [x] ~12. input device check, recommend `cuda`~
 - [x] ~10. "last dim 2" allows faster "complex * real"?~
 - [x] ~5. `alpha=5` -> `4`~
 - [x] ~5. `J_tentative` repeat `while support == N//2`~
 - [x] ~3. up is down~
