### ISSUE TITLE
JTFS is complete and ready for review

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#786]
I lived to see the day.
  
All work from purely my end is finished; remainder is to be handled by maintainers. Below I have detailed a TODO and recommended a merge order - here is [JTFS report](https://github.com/kymatio/kymatio/discussions/784). I may add to the PR on occasion, but all optional (examples, utilities, etc) - the implementation is complete. The additions will be on my own branch which will include [preallocation](https://github.com/kymatio/kymatio/issues/758) as I need the speed.

@lostanlen @janden @eickenberg @edouardoyallon 
  
<hr>
  
### TODO

In no particular order

 - [ ] 1. Merge constituent PRs
 - [ ] 2. Rebase into `dev` (main branch)
 - [ ] 3. #772 
 - [ ] 4. #758
 - [ ] 5. #771
 - [ ] 6. #783
 - [ ] 7. [Disagreement on throwing error](https://github.com/kymatio/kymatio/pull/729#issuecomment-829164613)
 - [ ] 8. [Disagreement on style](https://github.com/kymatio/kymatio/pull/714#issuecomment-829597923)

### Recommended merge order

Tried to break up into as many parts as possible without having to rewrite finished code

 - [ ] 1. #745 
 - [ ] 2. #673 
 - [ ] 3. #750 
 - [ ] 4. #725 
 - [ ] 5. #727 
 - [ ] 6. #734 
 - [ ] 7. #728 
 - [ ] 8. #739 

Next, in no particular order:

 - [ ] 9. #729 
 - [ ] 10. #736 
 - [ ] 11. #737 
 - [ ] 12. #738 
 - [ ] 13. #740 
 - [ ] 14. #742 
 - [ ] 15. #746 
 - [ ] 16. #763 
 - [ ] 17. #764 
 - [ ] 18. #765 
 - [ ] 19. #766 
 - [ ] 20. #770 

Then can begin JTFS, stripped nearly to barebones except for `core` and all that's required to run it, Numpy only:

 - [ ] 21. #781

That's 6k LOC as opposed to 13k, much of which is dosctrings. The remainder is mainly `visuals`, `toolkit`, and backends/frontends, which can be figured out afterwards.

### Reviewing the algorithm

Superficially, coverage and correctness tests should do. Beyond, see [reviewing `core`](https://github.com/kymatio/kymatio/issues/785).

### Reviewing documentation

In addition to docstrings, can build website-like from terminal

```
cd "kymatio\doc\"
sphinx-build -a -E 'source' 'build'
```
then open `kymatio\doc\build\index.html`. Requires environment with both PyTorch and TensorFlow installed; with Anaconda,

```
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
conda install -c anaconda tensorflow
```

**Comment by MuawizChaudhary** [comment]
Stale
